# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:digitalocean_db, :username) %>
  password: <%= Rails.application.credentials.dig(:digitalocean_db, :password) %>
  host: <%= Rails.application.credentials.dig(:digitalocean_db, :host) %>
  port: <%= Rails.application.credentials.dig(:digitalocean_db, :port) %>
  sslmode: require

development:
  <<: *default
  database: official02_development

test:
  <<: *default
  database: official02_test

production:
  url: <%= ENV['DATABASE_URL'] %>

